import { useState } from 'react';
import { Activity, Download, Search, ScanEye } from 'lucide-react';
import { downloadJSON } from '../data/api';
import { directionNames, format, type Snapshot } from '../domain/telemetry';

const kinds: Record<string,string> = { car:'Легковой',bus:'Автобус',truck:'Грузовик',motorcycle:'Мотоцикл',bicycle:'Велосипед',pedestrian:'Пешеход' };
export default function Analytics({ snapshot }: { snapshot: Snapshot | null }) {
  const [filter,setFilter] = useState('');
  const pipeline=snapshot?.pipeline; const tracks=(snapshot?.tracks ?? []).filter(t=>`${t.track_id} ${t.kind} ${kinds[t.kind]} ${t.lane}`.toLowerCase().includes(filter.toLowerCase()));
  return <div className="feature-page"><section className="card"><div className="card-head"><div><h2>Производительность pipeline</h2><p>{snapshot?.mode==='demo'?'Demo observations → Analysis → Decision → Safety':'Capture → Inference → Analysis → Publishing'}</p></div><Activity size={20} className="green-text"/></div>{pipeline?<><div className="pipeline-grid">{[['Захвачено',pipeline.captured],['Inference',pipeline.inferred],['Анализ',pipeline.analyzed],['Опубликовано',pipeline.published]].map(([label,value],i)=><div key={label}><span className="pipeline-step">0{i+1}</span><span>{label}</span><strong>{format(Number(value))}</strong></div>)}</div><div className="pipeline-summary"><span>Обработка <b>{format(pipeline.processing_fps,1)} FPS</b></span><span>Задержка <b>{format(pipeline.latency_ms,1)} мс</b></span><span>Пропущено <b>{format(pipeline.dropped_capture+pipeline.dropped_inference+pipeline.dropped_analysis)}</b></span><span>Состояние <b>{snapshot?.mode==='demo'?'demo / '+pipeline.state:pipeline.state}</b></span></div>{pipeline.error?<p className="error-text padded">{pipeline.error}</p>:null}</>:<div className="empty-small">В режиме Simulation камера и нейросеть не используются. Метрики CV появятся при запуске Vision.</div>}</section>
    {snapshot?.kpi?<section className="card"><div className="card-head"><h2>KPI текущей симуляции</h2><span className="badge blue">С начала сеанса</span></div><div className="simulation-kpis">{[['Прибыло',snapshot.kpi.arrived],['Обслужено',snapshot.kpi.departed],['Осталось',snapshot.kpi.remaining],['Пропускная способность, об./мин',snapshot.kpi.throughput_per_minute],['Ожидание на прибытие, с',snapshot.kpi.mean_wait_per_arrival_seconds],['Пиковая очередь',snapshot.kpi.max_queue]].map(([label,value])=><div key={label}><span>{label}</span><strong>{format(Number(value),1)}</strong></div>)}</div></section>:null}
    <section className="card"><div className="card-head"><div><h2>Объекты и трекинг <span className="count-pill">{tracks.length}</span></h2><p>Постоянный ID, направление, скорость и фактическое ожидание</p></div><button className="secondary-button" disabled={!snapshot} onClick={()=>downloadJSON(snapshot?.tracks,'traffic-tracks.json')}><Download size={16}/>Экспорт</button></div><div className="table-toolbar"><label className="search-input"><Search size={16}/><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="ID, класс или направление" aria-label="Поиск треков"/></label><span className="muted small">Уникальных прибытий: {format(snapshot?.unique)}</span></div><div className="table-scroll"><table><thead><tr><th>Track ID</th><th>Класс</th><th>Направление</th><th>Уверенность</th><th>Скорость</th><th>Ожидание</th><th>Состояние</th></tr></thead><tbody>{tracks.slice(0,200).map(track=><tr key={track.track_uid}><td className="mono" title={track.track_uid}>#{track.track_id}</td><td>{kinds[track.kind]??track.kind}</td><td>{directionNames[track.lane as keyof typeof directionNames]??'Не определено'}</td><td>{format(track.confidence*100)}%</td><td>{format(track.speed_px_per_second,1)} px/s</td><td>{format(track.current_wait_time,1)} с</td><td><span className={`badge ${track.queued?'amber':'green'}`}>{track.queued?'В очереди':'Вне очереди'}</span></td></tr>)}</tbody></table></div>{!tracks.length?<div className="empty"><ScanEye size={34} strokeWidth={1.4}/><h3>{snapshot?.mode==='simulation'?'Трекинг доступен в режиме Vision':'Нет подходящих треков'}</h3><p>{snapshot?.mode==='simulation'?'Запустите backend с камерой, видеофайлом или синтетическим источником.':'Новые объекты появятся здесь автоматически.'}</p></div>:null}{snapshot?.mode==='demo'?<p className="demo-table-note">DEMO: треки синтетические и нужны для презентации интерфейса. В REAL режиме таблица заполняется результатами настоящего Vision Engine.</p>:null}<p className="table-note">Скорость дана в опорных пикселях в секунду. Это не км/ч. Отображается до 200 текущих треков; экспорт содержит все.</p></section></div>;
}
