import { useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Download, FlaskConical, Play, ScanLine } from 'lucide-react';
import { downloadJSON, request } from '../data/api';
import { format, type Comparison as Result } from '../domain/telemetry';

export default function Comparison() {
  const [result,setResult] = useState<Result|null>(null);
  const [duration,setDuration] = useState(600); const [seed,setSeed] = useState(42);
  const [rates,setRates] = useState([18,12,5,4]);
  const [busy,setBusy] = useState(false); const [error,setError] = useState('');
  async function run(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError('');
    try { setResult(await request<Result>('/api/v1/simulation/compare','POST',{ duration_seconds:duration, scenario: { seed, north_per_minute:rates[0],south_per_minute:rates[1],east_per_minute:rates[2],west_per_minute:rates[3] } })); }
    catch(e) { setError(e instanceof Error?e.message:String(e)); }
    finally { setBusy(false); }
  }
  const improvement = result?.wait_reduction_percent;
  const positive = improvement != null && improvement >= 0;
  return <div className="feature-page"><div className="experiment-banner"><div><span className="eyebrow">ДОКАЗАТЕЛЬСТВА В ЦИФРАХ</span><h2>Один поток. Два подхода.</h2><p>Сравните обычный светофор и адаптивный AI на одинаковых прибытиях транспорта.</p></div><FlaskConical size={68} strokeWidth={1}/></div><div className="comparison-layout"><form className="card experiment-form" onSubmit={e=>void run(e)}><div className="card-head"><h2>Условия эксперимента</h2><ScanLine size={18}/></div><label>Продолжительность<select value={duration} onChange={e=>setDuration(+e.target.value)}><option value={60}>1 минута</option><option value={300}>5 минут</option><option value={600}>10 минут</option><option value={1800}>30 минут</option></select></label><label>Seed сценария<input type="number" min="0" max="2147483647" required value={seed} onChange={e=>setSeed(+e.target.value)}/></label><div className="form-divider"/><h3>Интенсивность, машин/мин</h3><div className="rate-grid">{['Север','Юг','Восток','Запад'].map((name,i)=><label key={name}>{name}<input type="number" min="0" max="120" step="1" required value={rates[i]} onChange={e=>setRates(old=>old.map((v,j)=>i===j?+e.target.value:v))}/></label>)}</div><p className="muted small">Пешеходы: 6/мин. Расчёт выполняется на backend и не меняет живой перекрёсток.</p><button className="primary-button full" disabled={busy}><Play size={16}/>{busy?'Рассчитываем…':'Запустить сравнение'}</button>{error?<p className="error-text" role="alert">{error}</p>:null}</form><section className="card comparison-result">{result?<><div className="card-head"><div><h2>Результат эксперимента</h2><p>Seed {result.seed} · {result.duration_seconds} с · одинаковый поток</p></div><button className="icon-button" aria-label="Скачать результаты сравнения" onClick={()=>downloadJSON(result,'traffic-comparison.json')}><Download size={19}/></button></div><div className={`improvement ${positive?'':'negative'}`}>{positive?<ArrowDownRight size={35}/>:<ArrowUpRight size={35}/>}<strong>{format(improvement==null?null:Math.abs(improvement),1)}<small>%</small></strong><span>{improvement==null?'Нет ожидания для сравнения':positive?'меньше суммарного ожидания':'больше суммарного ожидания'}</span></div><div className="compare-legend"><span><i className="legend-dot gray"/>Fixed-Time</span><span><i className="legend-dot green"/>Smart Traffic AI</span></div>{([
      ['Среднее ожидание на прибытие','mean_wait_per_arrival_seconds','с'],['Пропускная способность','throughput_per_minute','об./мин'],['Обслужено объектов','departed',''],['Максимальная очередь','max_queue','об.'],['Осталось в системе','remaining','об.'],
    ] as const).map(([label,key,unit])=><div className="compare-row" key={key}><h3>{label}</h3>{(['fixed','adaptive'] as const).map(policy=><div key={policy}><div className={`compare-bar ${policy}`} style={{width:`${Math.max(1,result[policy][key]/Math.max(1,result.fixed[key],result.adaptive[key])*80)}%`}}/><b>{format(result[policy][key],1)} <small>{unit}</small></b></div>)}</div>)}<p className="comparison-disclaimer">Результат математической симуляции, не измерение на реальной дороге. При изменении сценария эффект может быть отрицательным.</p></>:<div className="empty experiment-empty"><FlaskConical size={44} strokeWidth={1.2}/><h2>Пусть алгоритмы покажут результат</h2><p>Задайте поток и запустите честный парный эксперимент. Здесь появятся измеренные KPI.</p></div>}</section></div></div>;
}
